services:
  kaspi-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:9090
    volumes:
      - ./Jetqor kaspi api/appsettings.json:/app/appsettings.json:ro
